.enum GSS
	DELAY      = 0   ; Up to 148
	NOTE       = 149 ; C1-B8, up to 254
	KEYOFF     = 245 ;
	LONGDELAY  = 246 ; L H
	VOLUME     = 247 ; V
	PAN        = 248 ; P
	DETUNE     = 249 ; D
	SLIDE      = 250 ; S
	PORTAMENTO = 251 ; P
	VIBRATO    = 252 ; M
	REFERENCE  = 253 ; L H C - absolute address, reference length
	INSTRUMENT = 254 ; I     - instrument change
	LOOP       = 255 ; L H   - absolute address of loop point
.endenum
