.globalzp retraces
.globalzp keydown
.globalzp keylast
.globalzp keynew
.globalzp ScrollX
.globalzp ScrollY
.globalzp LevelBlockPtr
.globalzp PlayerPX
.globalzp PlayerPY
.globalzp PlayerVX
.globalzp PlayerVY
.globalzp PlayerFrame
.globalzp PlayerDir
.globalzp PlayerWasRunning
.globalzp OamPtr
.globalzp TempVal
.globalzp TempX
.globalzp TempY
.global PlayerAccelSpeed
.global PlayerDecelSpeed

.global ColumnUpdateAddress
.global ColumnUpdateBuffer
.global RowUpdateAddress
.global RowUpdateBuffer
.global LevelBuf
.global OAM
.global OAMHI


